import { Impression } from './types.js';

export const mockImpressions: Impression[] = [
  {
    id: 'imp-001',
    publisherId: 'techcrunch',
    slotSize: '300x250',
    userSegment: 'tech',
    location: 'San Francisco',
    floorPrice: 0.15,
  },
  {
    id: 'imp-002',
    publisherId: 'wsj',
    slotSize: '728x90',
    userSegment: 'finance',
    location: 'New York',
    floorPrice: 0.25,
  },
  {
    id: 'imp-003',
    publisherId: 'medium',
    slotSize: '300x250',
    userSegment: 'tech',
    location: 'London',
    floorPrice: 0.1,
  },
  {
    id: 'imp-004',
    publisherId: 'espn',
    slotSize: '160x600',
    userSegment: 'sports',
    location: 'Los Angeles',
    floorPrice: 0.12,
  },
  {
    id: 'imp-005',
    publisherId: 'cnn',
    slotSize: '300x250',
    userSegment: 'general',
    location: 'New York',
    floorPrice: 0.11,
  },
  {
    id: 'imp-006',
    publisherId: 'reuters',
    slotSize: '728x90',
    userSegment: 'finance',
    location: 'London',
    floorPrice: 0.16,
  },
  {
    id: 'imp-007',
    publisherId: 'github',
    slotSize: '300x250',
    userSegment: 'tech',
    location: 'San Francisco',
    floorPrice: 0.14,
  },
  {
    id: 'imp-008',
    publisherId: 'reddit',
    slotSize: '300x250',
    userSegment: 'general',
    location: 'Austin',
    floorPrice: 0.08,
  },
  {
    id: 'imp-009',
    publisherId: 'bloomberg',
    slotSize: '728x90',
    userSegment: 'finance',
    location: 'New York',
    floorPrice: 0.2,
  },
  {
    id: 'imp-010',
    publisherId: 'arstechnica',
    slotSize: '160x600',
    userSegment: 'tech',
    location: 'Chicago',
    floorPrice: 0.13,
  },
];
